### ISSUE TITLE
Knex error

### ISSUE THREAD

**Issue by lovelamp** [adonis-china/adonis-admin#1]
do i have to install node version 5.9?

citc@citc:~/adonis-admin$ npm run serve:dev

> adonis-app@3.2.1 serve:dev /home/citc/adonis-admin
> nodemon --watch app --watch bootstrap --watch config --watch .env -x node server.js

[nodemon] 1.14.11
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: /home/citc/adonis-admin/app/**/* /home/citc/adonis-admin/bootstrap/**/* /home/citc/adonis-admin/config/**/* .env
[nodemon] starting `node server.js`
info adonis:framework +0ms serving app on localhost:3333
Knex: run
$ npm install sqlite3 --save
Error: Cannot find module '/home/citc/adonis-admin/node_modules/sqlite3/lib/binding/node-v59-linux-x64/node_sqlite3.node'
    at Function.Module._resolveFilename (module.js:555:15)
    at Function.Module._load (module.js:482:25)
    at Module.require (module.js:604:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/citc/adonis-admin/node_modules/sqlite3/lib/sqlite3.js:4:15)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
    at Module.require (module.js:604:17)
    at require (internal/module.js:11:18)
    at Client_SQLite3._driver (/home/citc/adonis-admin/node_modules/knex/lib/dialects/sqlite3/index.js:75:12)
    at Client_SQLite3.initializeDriver (/home/citc/adonis-admin/node_modules/knex/lib/client.js:219:26)
    at Client_SQLite3.Client (/home/citc/adonis-admin/node_modules/knex/lib/client.js:113:10)
    at new Client_SQLite3 (/home/citc/adonis-admin/node_modules/knex/lib/dialects/sqlite3/index.js:58:20)
[nodemon] app crashed - waiting for file changes before starting...

**Comment by lovelamp** [comment]
the error got fixed by 
`rm-rf node_modules`
then run
`npm install` without root.

thannks
